# Generated by Django 2.0.5 on 2018-06-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicelocation', '0006_devicelocation_server_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelocation',
            name='server_timestamp',
            field=models.IntegerField(),
        ),
    ]
