# Generated by Django 2.0.5 on 2018-05-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicelocation', '0002_auto_20180530_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicelocation',
            old_name='alt',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='devicelocation',
            old_name='deviceID',
            new_name='altitude',
        ),
        migrations.RenameField(
            model_name='devicelocation',
            old_name='aid',
            new_name='android_id',
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='annotation',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='battery',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='direction',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='file',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='hdop',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='pdop',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='profile',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='provider',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='satellites',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='serial',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='start_timestamp',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='utc_time',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='vdop',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
