# Generated by Django 2.0.5 on 2018-06-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicelocation', '0005_devicelocation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelocation',
            name='server_timestamp',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
