# Generated by Django 2.0.5 on 2018-05-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicelocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelocation',
            name='aid',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='alt',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
